# Generated by Django 4.2.6 on 2023-11-04 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_studentlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='students',
        ),
        migrations.AlterField(
            model_name='studentlist',
            name='student',
            field=models.ManyToManyField(to='mainapp.student'),
        ),
    ]
