# Generated by Django 4.2.6 on 2023-10-22 17:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0002_subject_prof'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='cid',
        ),
        migrations.AddField(
            model_name='class',
            name='students',
            field=models.ManyToManyField(to='mainapp.student'),
        ),
        migrations.RemoveField(
            model_name='subject',
            name='cid',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='prof',
        ),
        migrations.AddField(
            model_name='subject',
            name='cid',
            field=models.ManyToManyField(to='mainapp.class'),
        ),
        migrations.AddField(
            model_name='subject',
            name='prof',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
