# Generated by Django 4.2.6 on 2023-10-22 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_remove_student_cid_class_students_remove_subject_cid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='students',
            field=models.ManyToManyField(blank=True, null=True, to='mainapp.student'),
        ),
    ]
