# Generated by Django 4.2.6 on 2023-10-23 11:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0005_subject_students_remove_subject_prof_subject_prof'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='prof',
        ),
        migrations.AddField(
            model_name='subject',
            name='prof',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
