# Generated by Django 4.2.6 on 2023-10-23 13:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0009_alter_subject_prof'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('sid', 'cid')},
        ),
        migrations.RemoveField(
            model_name='subject',
            name='cid',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='prof',
        ),
        migrations.AddField(
            model_name='subject',
            name='cid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mainapp.class'),
        ),
        migrations.AddField(
            model_name='subject',
            name='prof',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
