# Generated by Django 4.2.6 on 2023-10-23 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_alter_subject_unique_together_alter_subject_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='students',
            field=models.ManyToManyField(blank=True, null=True, to='mainapp.student'),
        ),
    ]
