# Generated by Django 4.2.6 on 2023-11-01 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_student_cid_alter_class_students_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='classno',
            field=models.IntegerField(default=1),
        ),
    ]
