# Generated by Django 4.2.6 on 2023-11-02 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_attendance_classno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='cid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.class'),
        ),
    ]
